demandimport: skip OpenSSL.SSL when performing lazy imports
The OpenSSL.SSL module from pyopenssl doesn't support lazy loading when
used with requests probably due to the way the requests module injects
pyopenssl into urllib3.

The relevant traceback when performing a lazy load is the following:

  File "/usr/lib64/python3.6/site-packages/requests/__init__.py", line 96, in <module>
    pyopenssl.inject_into_urllib3()
  File "/usr/lib64/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/usr/lib64/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 80, in <module>
    ssl.PROTOCOL_SSLv23: OpenSSL.SSL.SSLv23_METHOD,
  File "/usr/lib64/python3.6/importlib/util.py", line 238, in __getattribute__
    raise ValueError(f"module object for {original_name!r} "
ValueError: module object for 'OpenSSL.SSL' substituted in sys.modules during a lazy load