tar: fix uname/gname properties under py3
Fixes the following errors which are raised when creating binpkgs:
AttributeError: 'TarInfo' object has no attribute '_uname'